import React,{useMemo,useState} from "react";
import {Pressable,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import {colors} from "../styles/colors";
export default function ConfiguracoesScreen({dark,onToggleDark,onLogout,userName}){const t=dark?colors.dark:colors.light;const[name,setName]=useState(userName||"Usuário");const[draft,setDraft]=useState(userName||"Usuário");const[edit,setEdit]=useState(false);const[search,setSearch]=useState("");const sections=[{title:"Conta",items:["Idioma","Centro de atividades","Acessibilidade"]},{title:"Ajuda e privacidade",items:["Central de ajuda","Central de privacidade","Termos e políticas"]}];const filtered=useMemo(()=>{let q=search.trim().toLowerCase();if(!q)return sections;return sections.map(s=>({...s,items:s.items.filter(i=>`${s.title} ${i}`.toLowerCase().includes(q))})).filter(s=>s.items.length)},[search]);const save=()=>{if(draft.trim())setName(draft.trim());setEdit(false)};return <ScrollView style={{backgroundColor:t.background}} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
<View style={[s.profile,{backgroundColor:t.greenLight}]}><View style={s.avatar}><Text style={{fontSize:28}}>👤</Text></View><View style={{flex:1}}>{edit?<View style={s.editRow}><TextInput autoFocus value={draft} onChangeText={setDraft} onSubmitEditing={save} style={[s.nameInput,{color:t.text,borderColor:t.green}]}/><Pressable onPress={save} style={[s.ok,{backgroundColor:t.green}]}><Text style={{color:'#fff',fontWeight:'800'}}>OK</Text></Pressable></View>:<><Text style={[s.name,{color:t.text}]}>{name}</Text><Text style={{color:t.text}}>Admin</Text></>}</View><Pressable onPress={()=>{setDraft(name);setEdit(v=>!v)}}><Text style={{color:t.green,fontSize:23}}>✎</Text></Pressable></View>
<View style={[s.search,{backgroundColor:t.mint}]}><Text style={{color:t.muted,fontSize:18}}>⌕</Text><TextInput value={search} onChangeText={setSearch} placeholder="Pesquisar configurações..." placeholderTextColor={t.muted} style={[s.searchInput,{color:t.text}]}/>{!!search&&<Pressable onPress={()=>setSearch("")}><Text style={{color:t.muted,fontSize:18}}>×</Text></Pressable>}</View>
{filtered.length?filtered.map(sec=><View key={sec.title} style={[s.box,{backgroundColor:t.cream}]}><Text style={[s.section,{color:t.text}]}>{sec.title}</Text>{sec.items.map(item=><Pressable key={item} style={s.option}><Text style={{color:t.text}}>{item}</Text><Text style={{color:t.muted}}>›</Text></Pressable>)}</View>):<View style={[s.empty,{backgroundColor:t.cream}]}><Text style={{color:t.text}}>Nenhuma configuração encontrada para "{search}".</Text></View>}
<View style={[s.themeCard,{backgroundColor:t.beige}]}><View style={{flex:1}}><Text style={[s.section,{color:t.text}]}>Aparência</Text><Text style={{color:t.muted}}>{dark?'Modo escuro ativado':'Modo claro ativado'}</Text></View><Pressable onPress={onToggleDark} style={[s.themeBtn,{backgroundColor:t.green}]}><Text style={{color:'#fff',fontWeight:'800'}}>{dark?'Modo claro':'Modo escuro'}</Text></Pressable></View><Pressable onPress={onLogout} style={s.logout}><Text style={{color:t.text,fontWeight:'800'}}>↪ Sair</Text></Pressable>
</ScrollView>}
const s=StyleSheet.create({content:{padding:16,paddingBottom:40},profile:{flexDirection:'row',alignItems:'center',padding:12,borderRadius:14,marginBottom:12},avatar:{width:54,height:54,borderRadius:27,backgroundColor:'#CCC',alignItems:'center',justifyContent:'center',marginRight:10},name:{fontWeight:'900',fontSize:17},editRow:{flexDirection:'row',alignItems:'center',gap:6},nameInput:{borderBottomWidth:2,minWidth:120,height:38},ok:{paddingHorizontal:10,paddingVertical:7,borderRadius:10},search:{minHeight:44,borderRadius:22,paddingHorizontal:14,flexDirection:'row',alignItems:'center',marginBottom:12},searchInput:{flex:1,paddingHorizontal:8,minHeight:42},box:{padding:14,borderRadius:14,marginBottom:12},section:{fontWeight:'900',fontSize:15,marginBottom:6},option:{paddingVertical:11,flexDirection:'row',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'rgba(120,120,120,.15)'},themeCard:{padding:14,borderRadius:14,flexDirection:'row',alignItems:'center',gap:10},themeBtn:{paddingHorizontal:12,paddingVertical:9,borderRadius:14},empty:{padding:18,borderRadius:14},logout:{paddingVertical:20}});
